### ISSUE TITLE
端口冲突问题

### ISSUE THREAD

**Issue by BoyuZhou** [tinper-uba/uba-server#1]
某些时候，启动服务后，在gitbash使用ctrl+c停止当前服务时，并没有停止express服务，造成端口冲突，无法再次启动，还需要去任务管理关闭node服务。
解决建议，一个是ctrl+c后停止服务，另一个可以在服务内部进行处理，如果端口占用，启用相邻端口。

**Comment by kvkens** [comment]
确实是有这么个问题，我记录下，着手搞一下 ~ thinks~

**Comment by kvkens** [comment]
未来版本1.0.0增加此功能。
# af2604e7c9309925078e089fefa115e6e7bd0393
