### ISSUE TITLE
端口占用问题和远程访问问题

### ISSUE THREAD

**Issue by zerooneshang** [tinper-uba/uba-server#3]
本地3000端口已经被占用，启动服务已经自动换成3001了，但是打开浏览器还是127.0.0.1:3000，得手动改成3001才能访问，还有，能否参照create-react-app，既可以访问localhost，也可以通过ip访问，方便其他人调试本地代码，谢谢

**Comment by kvkens** [comment]
自动打开浏览器插件的问题，下一版把该插件集成到server里面。

**Comment by kvkens** [comment]
IP修改为`0.0.0.0`就可以访问`localhost`和`127.0.0.1`

**Comment by kvkens** [comment]
感谢使用`uba`，后面可以关注下[uba-gui](https://github.com/tinper-uba/uba-gui)，一款可视化操作跨平台使用的版本。

**Comment by zerooneshang** [comment]
@kvkens 感谢您的回复，使用0.0.0.0可以localhost访问也可以127.0.0.1访问也可以网络ip访问，同样打开默认浏览器也变成0.0.0.0:3000了，这个问题还是存在，uba-gui我搜索看下^^

**Comment by kvkens** [comment]
@zerooneshang 嗯是有这问题，当时也想到了，忙完GUI版后，cli版本我会解决这几个小问题，十分感谢反馈~！
